-- ============================================================================
-- Base schema: events / categories / tasks / todos  (+ RLS)
-- ----------------------------------------------------------------------------
-- These four tables hold all of the app's real user data but previously had
-- NO CREATE TABLE / RLS definition in version control — they existed only in
-- the live database (created via the Supabase dashboard). This migration
-- codifies the current production schema (verified 2026-06-29 against project
-- oungvayvmxkszsokxwxd) so that a fresh database / disaster-recovery rebuild
-- reproduces the tables AND their Row Level Security.
--
-- IMPORTANT: production already has these tables with RLS enabled and correct
-- per-user policies. This file is intentionally idempotent (IF NOT EXISTS /
-- DROP POLICY IF EXISTS) and is meant for fresh environments; it is NOT applied
-- to the existing production DB. It must run BEFORE the later ALTER migrations
-- (20260521_overtime.sql, 20260610_reminder_minutes.sql) which add columns to
-- `events` and use `ADD COLUMN IF NOT EXISTS`.
-- ============================================================================

-- updated_at trigger function (search_path pinned per security advisor) --------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- events ---------------------------------------------------------------------
create table if not exists public.events (
  id               bigserial primary key,
  user_id          uuid not null references auth.users(id) on delete cascade,
  date_key         text not null,
  cat_id           integer not null,
  title            text not null default '',
  time             text,
  shift_start      text,
  shift_end        text,
  break_minutes    integer default 0,
  time_end         text,
  overtime_minutes integer not null default 0,
  reminder_minutes integer,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);
create index if not exists events_user_id_idx on public.events (user_id);

alter table public.events enable row level security;
drop policy if exists "own events" on public.events;
create policy "own events" on public.events
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at before update on public.events
  for each row execute function public.set_updated_at();

-- categories -----------------------------------------------------------------
create table if not exists public.categories (
  id          bigserial primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  cat_id      integer not null,
  name        text not null,
  color       text not null,
  type        text not null default 'normal',
  hourly_wage integer,
  templates   jsonb default '[]'::jsonb,
  sort_order  integer default 0,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);
create index if not exists categories_user_id_idx on public.categories (user_id);
-- Required by the app's upsert(onConflict: 'user_id,cat_id') when seeding /
-- saving categories; without it a fresh DB raises 42P10 on first login.
create unique index if not exists categories_user_cat_uniq on public.categories (user_id, cat_id);

alter table public.categories enable row level security;
drop policy if exists "own categories" on public.categories;
create policy "own categories" on public.categories
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at before update on public.categories
  for each row execute function public.set_updated_at();

-- tasks ----------------------------------------------------------------------
create table if not exists public.tasks (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  task_id    text not null,
  title      text not null default '',
  done       boolean not null default false,
  priority   text not null default 'medium',
  due_date   text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists tasks_user_id_idx on public.tasks (user_id);

alter table public.tasks enable row level security;
drop policy if exists "own tasks" on public.tasks;
create policy "own tasks" on public.tasks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop trigger if exists set_tasks_updated_at on public.tasks;
create trigger set_tasks_updated_at before update on public.tasks
  for each row execute function public.set_updated_at();

-- todos ----------------------------------------------------------------------
create table if not exists public.todos (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  scope      text not null,
  scope_key  text not null,
  todo_id    text not null,
  text       text not null default '',
  done       boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists todos_user_id_idx on public.todos (user_id);

alter table public.todos enable row level security;
drop policy if exists "own todos" on public.todos;
create policy "own todos" on public.todos
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop trigger if exists set_todos_updated_at on public.todos;
create trigger set_todos_updated_at before update on public.todos
  for each row execute function public.set_updated_at();
